import { RawProject, ImplementingAgency, BillRecord } from './types';

export const INITIAL_AGENCIES: ImplementingAgency[] = [
  {
    agency_id: "AG-CHE-01",
    agency_name: "Apex Infrastructure & Works Ltd",
    registration_ref: "33AAACA1122D1Z4", // Tamil Nadu GSTIN format
    contact_person: "K. Ramanathan",
    contact_phone: "+91 98401 23456",
    contact_email: "ramanathan@apexinfra.in",
    registered_address: "14, Mount Road, Anna Salai, Chennai 600002",
    associated_projects: ["MPLAD001", "MPLAD013"],
    previous_projects_completed: 18,
    verification_status: "Possible Duplicate / Inconsistent Agency Record",
    verification_notes: "Multiple trade names associated with same PAN/GSTIN registration reference across districts."
  },
  {
    agency_id: "AG-VEL-02",
    agency_name: "Vellore Engineering Services",
    registration_ref: "33BBBPB9876C1Z9",
    contact_person: "S. Venkatesh",
    contact_phone: "+91 94432 77112",
    contact_email: "contact@velloreengg.com",
    registered_address: "45, Gandhi Nagar Main Road, Vellore 632006",
    associated_projects: ["MPLAD002", "MPLAD008", "MPLAD020"],
    previous_projects_completed: 12,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  },
  {
    agency_id: "AG-SAL-03",
    agency_name: "Salem Civil & Water Utilities Pvt Ltd",
    registration_ref: "33AABCS4455E1Z1",
    contact_person: "M. Soundararajan",
    contact_phone: "+91 94433 88990",
    contact_email: "salem.civil@scwu.co.in",
    registered_address: "88, Omalur Main Road, Salem 636009",
    associated_projects: ["MPLAD003", "MPLAD009", "MPLAD015"],
    previous_projects_completed: 15,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  },
  {
    agency_id: "AG-MAD-04",
    agency_name: "Madurai Public Works Consortium",
    registration_ref: "33AABCM3322K1Z5",
    contact_person: "R. Meenakshisundaram",
    contact_phone: "+91 98421 55667",
    contact_email: "madurai.pwc@gmail.com",
    registered_address: "102, West Masi Street, Madurai 625001",
    associated_projects: ["MPLAD004", "MPLAD010"],
    previous_projects_completed: 9,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  },
  {
    agency_id: "AG-COI-05",
    agency_name: "Kongu Infra Developments",
    registration_ref: "33AABCK9911P1Z3",
    contact_person: "C. Balasubramaniam",
    contact_phone: "+91 98430 11223",
    contact_email: "info@konguinfra.in",
    registered_address: "56, Avinashi Road, Peelamedu, Coimbatore 641004",
    associated_projects: ["MPLAD005", "MPLAD011", "MPLAD017"],
    previous_projects_completed: 22,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  },
  {
    agency_id: "AG-TRI-06",
    agency_name: "Delta Buildcon Enterprises",
    registration_ref: "33AABCD6677F1Z8",
    contact_person: "A. Xavier",
    contact_phone: "+91 94440 66554",
    contact_email: "xavier@deltabuild.org",
    registered_address: "21, Salai Road, Thillai Nagar, Trichy 620018",
    associated_projects: ["MPLAD006", "MPLAD012", "MPLAD018"],
    previous_projects_completed: 14,
    verification_status: "Verification Required",
    verification_notes: "Pending updated annual GST filing verification for fiscal year 2024."
  },
  {
    agency_id: "AG-CHE-07",
    agency_name: "Metro Urban Drainage Contractors",
    registration_ref: "33AAACM5544J1Z7",
    contact_person: "P. Jayakumar",
    contact_phone: "+91 98840 99887",
    contact_email: "jayakumar@metrodrain.in",
    registered_address: "32, Nelson Manickam Road, Aminjikarai, Chennai 600029",
    associated_projects: ["MPLAD007", "MPLAD019"],
    previous_projects_completed: 11,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  },
  {
    agency_id: "AG-MAD-08",
    agency_name: "Star Health Infrastructure Partners",
    registration_ref: "33AAACS7788M1Z2",
    contact_person: "T. Rajkumar",
    contact_phone: "+91 98425 44332",
    contact_email: "admin@starhealthinfra.com",
    registered_address: "73, Alagarkoil Road, Tallakulam, Madurai 625002",
    associated_projects: ["MPLAD016"],
    previous_projects_completed: 4,
    verification_status: "Possible Duplicate / Inconsistent Agency Record",
    verification_notes: "Agency ID AG-MAD-08 shares identical PAN reference with entity registered under another company."
  },
  {
    agency_id: "AG-VEL-09",
    agency_name: "Ranipet Pipeline Corp",
    registration_ref: "33AABCR1234N1Z6",
    contact_person: "D. Anand",
    contact_phone: "+91 94431 22334",
    contact_email: "anand@ranipetpipes.com",
    registered_address: "12, MBT Road, Ranipet, Vellore 632401",
    associated_projects: ["MPLAD014"],
    previous_projects_completed: 8,
    verification_status: "Agency Information Consistent",
    verification_notes: "Available agency information is consistent with the provided records."
  }
];

export const INITIAL_BILLS: BillRecord[] = [
  {
    bill_id: "BILL-2024-001",
    invoice_number: "INV/CHE/2024/089",
    project_id: "MPLAD001",
    project_name: "School Building",
    vendor_name: "Apex Infrastructure & Works Ltd",
    gstin_pan: "33AAACA1122D1Z4",
    amount: 1950000,
    bill_date: "2024-03-15",
    document_type: "Foundation & RCC Invoice",
    verification_status: "Possible Duplicate/Inconsistency",
    verification_notes: "Duplicate invoice number INV/CHE/2024/089 previously submitted for another regional sub-contract.",
    ocr_extracted: true,
    uploaded_at: "2024-03-16 11:30"
  },
  {
    bill_id: "BILL-2024-002",
    invoice_number: "INV/CHE/2024/089", // exact duplicate test record
    project_id: "MPLAD001",
    project_name: "School Building",
    vendor_name: "Apex Infrastructure & Works Ltd",
    gstin_pan: "33AAACA1122D1Z4",
    amount: 1950000,
    bill_date: "2024-03-15",
    document_type: "Masonry Stage Claim",
    verification_status: "Possible Duplicate/Inconsistency",
    verification_notes: "Same invoice number and amount submitted twice for Project MPLAD001.",
    ocr_extracted: true,
    uploaded_at: "2024-03-20 14:15"
  },
  {
    bill_id: "BILL-2024-003",
    invoice_number: "INV/VEL/2024/104",
    project_id: "MPLAD002",
    project_name: "Road Construction",
    vendor_name: "Vellore Engineering Services",
    gstin_pan: "33BBBPB9876C1Z9",
    amount: 1500000,
    bill_date: "2024-02-10",
    document_type: "Bitumen & Tar Laying Invoice",
    verification_status: "No Obvious Anomaly",
    verification_notes: "Document appears consistent with available records.",
    ocr_extracted: true,
    uploaded_at: "2024-02-12 09:45"
  },
  {
    bill_id: "BILL-2024-004",
    invoice_number: "INV/SAL/2024/033",
    project_id: "MPLAD003",
    project_name: "Water Tank",
    vendor_name: "Salem Civil & Water Utilities Pvt Ltd",
    gstin_pan: "33AABCS4455E1Z1",
    amount: 800000,
    bill_date: "2024-01-20",
    document_type: "Overhead Tank Casting Invoice",
    verification_status: "No Obvious Anomaly",
    verification_notes: "Document appears consistent with available records.",
    ocr_extracted: true,
    uploaded_at: "2024-01-22 16:00"
  },
  {
    bill_id: "BILL-2024-005",
    invoice_number: "INV/MAD/2024/210",
    project_id: "MPLAD016",
    project_name: "Primary Health Centre",
    vendor_name: "Star Health Infrastructure Partners",
    gstin_pan: "33AAACS7788M1Z2",
    amount: 2450000,
    bill_date: "2024-04-05",
    document_type: "Civil Structure Stage 1",
    verification_status: "Possible Duplicate/Inconsistency",
    verification_notes: "Duplicate vendor + amount combination detected with identical date submitted under dual vouchers.",
    ocr_extracted: true,
    uploaded_at: "2024-04-08 10:20"
  },
  {
    bill_id: "BILL-2024-006",
    invoice_number: "INV/TRI/2024/115",
    project_id: "MPLAD012",
    project_name: "Community Centre",
    vendor_name: "Delta Buildcon Enterprises",
    gstin_pan: "33AABCD6677F1Z8",
    amount: 1550000,
    bill_date: "2024-04-12",
    document_type: "Structural Framework Invoice",
    verification_status: "Needs Verification",
    verification_notes: "Supporting vendor GST tax invoice attachment is pending physical stamp verification.",
    ocr_extracted: true,
    uploaded_at: "2024-04-14 13:10"
  }
];

export const INITIAL_PROJECTS: RawProject[] = [
  {
    project_id: "MPLAD001",
    project_name: "School Building",
    district: "Chennai",
    category: "Education",
    approved_amount: 4000000,
    spent_amount: 3900000,
    progress_percent: 25,
    delay_days: 80,
    completion_status: "Ongoing",
    delay_reason: "Other / Unknown",
    supporting_event: "None reported by executing agency",
    supporting_document: "None / Inspection Notice Unanswered",
    approved_extension: false,
    extension_days: 0,
    agency_id: "AG-CHE-01",
    agency_name: "Apex Infrastructure & Works Ltd"
  },
  {
    project_id: "MPLAD002",
    project_name: "Road Construction",
    district: "Vellore",
    category: "Road",
    approved_amount: 5000000,
    spent_amount: 3000000,
    progress_percent: 65,
    delay_days: 10,
    completion_status: "Ongoing",
    delay_reason: "Material Supply Delay",
    supporting_event: "Aggregate supply transport strike (4 days)",
    supporting_document: "PWD Road Material Interruption Registry Memo PWD/VEL/2024/04",
    approved_extension: true,
    extension_days: 15,
    agency_id: "AG-VEL-02",
    agency_name: "Vellore Engineering Services"
  },
  {
    project_id: "MPLAD003",
    project_name: "Water Tank",
    district: "Salem",
    category: "Water Supply",
    approved_amount: 2000000,
    spent_amount: 1200000,
    progress_percent: 60,
    delay_days: 5,
    completion_status: "Ongoing",
    delay_reason: "Heavy Rainfall",
    supporting_event: "Intermittent pre-monsoon showers",
    supporting_document: "IMD Salem Weather Bulletin IMD/SAL/2024/09",
    approved_extension: true,
    extension_days: 10,
    agency_id: "AG-SAL-03",
    agency_name: "Salem Civil & Water Utilities Pvt Ltd"
  },
  {
    project_id: "MPLAD004",
    project_name: "Community Hall",
    district: "Madurai",
    category: "Community",
    approved_amount: 3500000,
    spent_amount: 1500000,
    progress_percent: 45,
    delay_days: 20,
    completion_status: "Ongoing",
    delay_reason: "Government Approval Delay",
    supporting_event: "Fire safety layout revision clearance",
    supporting_document: "Madurai Fire & Rescue Services Layout Approval Letter FIR/MAD/2024/44",
    approved_extension: true,
    extension_days: 30,
    agency_id: "AG-MAD-04",
    agency_name: "Madurai Public Works Consortium"
  },
  {
    project_id: "MPLAD005",
    project_name: "Street Lighting",
    district: "Coimbatore",
    category: "Infrastructure",
    approved_amount: 1500000,
    spent_amount: 1400000,
    progress_percent: 90,
    delay_days: 5,
    completion_status: "Ongoing",
    delay_reason: "Material Supply Delay",
    supporting_event: "LED fixture batch delivery delay",
    supporting_document: "TANGEDCO Electrical Delivery Manifest",
    approved_extension: true,
    extension_days: 10,
    agency_id: "AG-COI-05",
    agency_name: "Kongu Infra Developments"
  },
  {
    project_id: "MPLAD006",
    project_name: "School Renovation",
    district: "Trichy",
    category: "Education",
    approved_amount: 2500000,
    spent_amount: 800000,
    progress_percent: 30,
    delay_days: 60,
    completion_status: "Delayed",
    delay_reason: "Heavy Rainfall",
    supporting_event: "Cauvery Delta Monsoon Flooding Alert Nov 2024",
    supporting_document: "Tamil Nadu SDMA Flood Emergency Relief Notification SDMA/TRI/2024/08",
    approved_extension: true,
    extension_days: 60,
    agency_id: "AG-TRI-06",
    agency_name: "Delta Buildcon Enterprises"
  },
  {
    project_id: "MPLAD007",
    project_name: "Drainage Project",
    district: "Chennai",
    category: "Infrastructure",
    approved_amount: 3000000,
    spent_amount: 2800000,
    progress_percent: 40,
    delay_days: 70,
    completion_status: "Delayed",
    delay_reason: "Government Approval Delay",
    supporting_event: "Coastal CRZ clearance & High Tide boundary survey",
    supporting_document: "TNCZMA Coastal Regulation Clearance Resolution 14/CZMA/2024",
    approved_extension: true,
    extension_days: 90,
    agency_id: "AG-CHE-07",
    agency_name: "Metro Urban Drainage Contractors"
  },
  {
    project_id: "MPLAD008",
    project_name: "Health Centre",
    district: "Vellore",
    category: "Healthcare",
    approved_amount: 4500000,
    spent_amount: 2000000,
    progress_percent: 55,
    delay_days: 15,
    completion_status: "Ongoing",
    delay_reason: "Government Approval Delay",
    supporting_event: "Hospital equipment electrification blueprint approval",
    supporting_document: "DMS Healthcare Electrification Compliance Order DMS/VEL/2024/19",
    approved_extension: true,
    extension_days: 20,
    agency_id: "AG-VEL-02",
    agency_name: "Vellore Engineering Services"
  },
  {
    project_id: "MPLAD009",
    project_name: "Bus Shelter",
    district: "Salem",
    category: "Transport",
    approved_amount: 1000000,
    spent_amount: 950000,
    progress_percent: 85,
    delay_days: 3,
    completion_status: "Ongoing",
    delay_reason: "Material Supply Delay",
    supporting_event: "Stainless steel pipe transit delay",
    supporting_document: "State Transport Infrastructure Material Consignment Receipt",
    approved_extension: true,
    extension_days: 5,
    agency_id: "AG-SAL-03",
    agency_name: "Salem Civil & Water Utilities Pvt Ltd"
  },
  {
    project_id: "MPLAD010",
    project_name: "Library",
    district: "Madurai",
    category: "Education",
    approved_amount: 1800000,
    spent_amount: 1700000,
    progress_percent: 90,
    delay_days: 2,
    completion_status: "Ongoing",
    delay_reason: "Material Supply Delay",
    supporting_event: "Furniture finishing touch delay",
    supporting_document: "Madurai District Library Supply Order Acknowledgement",
    approved_extension: true,
    extension_days: 5,
    agency_id: "AG-MAD-04",
    agency_name: "Madurai Public Works Consortium"
  },
  {
    project_id: "MPLAD011",
    project_name: "Park Development",
    district: "Coimbatore",
    category: "Environment",
    approved_amount: 2200000,
    spent_amount: 1000000,
    progress_percent: 50,
    delay_days: 25,
    completion_status: "Ongoing",
    delay_reason: "Land / Permission Issue",
    supporting_event: "Municipal boundary demarcation survey",
    supporting_document: "Coimbatore Municipal Revenue Demarcation Gazette Order",
    approved_extension: true,
    extension_days: 30,
    agency_id: "AG-COI-05",
    agency_name: "Kongu Infra Developments"
  },
  {
    project_id: "MPLAD012",
    project_name: "Community Centre",
    district: "Trichy",
    category: "Community",
    approved_amount: 3200000,
    spent_amount: 3100000,
    progress_percent: 35,
    delay_days: 75,
    completion_status: "Delayed",
    delay_reason: "Other / Unknown",
    supporting_event: "No site inspection log submitted",
    supporting_document: "None / Inspection Notice Unacknowledged",
    approved_extension: false,
    extension_days: 0,
    agency_id: "AG-TRI-06",
    agency_name: "Delta Buildcon Enterprises"
  },
  {
    project_id: "MPLAD013",
    project_name: "Road Repair",
    district: "Chennai",
    category: "Road",
    approved_amount: 2800000,
    spent_amount: 2700000,
    progress_percent: 55,
    delay_days: 40,
    completion_status: "Ongoing",
    delay_reason: "Heavy Rainfall",
    supporting_event: "Northeast Monsoon Waterlogging in North Chennai",
    supporting_document: "Greater Chennai Corporation Inundation Notification GCC/MON/2024/31",
    approved_extension: true,
    extension_days: 45,
    agency_id: "AG-CHE-01",
    agency_name: "Apex Infrastructure & Works Ltd"
  },
  {
    project_id: "MPLAD014",
    project_name: "Water Pipeline",
    district: "Vellore",
    category: "Water Supply",
    approved_amount: 3800000,
    spent_amount: 1900000,
    progress_percent: 50,
    delay_days: 30,
    completion_status: "Ongoing",
    delay_reason: "Land / Permission Issue",
    supporting_event: "National Highway trenching permission wait",
    supporting_document: "NHAI Highway Right-of-Way Trenching Clearance NHAI/RO/VEL/2024/12",
    approved_extension: true,
    extension_days: 35,
    agency_id: "AG-VEL-09",
    agency_name: "Ranipet Pipeline Corp"
  },
  {
    project_id: "MPLAD015",
    project_name: "School Toilet",
    district: "Salem",
    category: "Education",
    approved_amount: 1200000,
    spent_amount: 1150000,
    progress_percent: 95,
    delay_days: 2,
    completion_status: "Completed",
    delay_reason: "Material Supply Delay",
    supporting_event: "Ceramic tile procurement delivery",
    supporting_document: "District Education Officer Inspection Certificate DEO/SAL/2024/02",
    approved_extension: true,
    extension_days: 5,
    agency_id: "AG-SAL-03",
    agency_name: "Salem Civil & Water Utilities Pvt Ltd"
  },
  {
    project_id: "MPLAD016",
    project_name: "Primary Health Centre",
    district: "Madurai",
    category: "Healthcare",
    approved_amount: 5000000,
    spent_amount: 4900000,
    progress_percent: 20,
    delay_days: 90,
    completion_status: "Delayed",
    delay_reason: "Contractor Issue",
    supporting_event: "Executing contractor stopped work without notice",
    supporting_document: "Default Notice PWD/MAD/2024/88 (No Extension)",
    approved_extension: false,
    extension_days: 0,
    agency_id: "AG-MAD-08",
    agency_name: "Star Health Infrastructure Partners"
  },
  {
    project_id: "MPLAD017",
    project_name: "Footpath",
    district: "Coimbatore",
    category: "Road",
    approved_amount: 1600000,
    spent_amount: 700000,
    progress_percent: 45,
    delay_days: 15,
    completion_status: "Ongoing",
    delay_reason: "Government Approval Delay",
    supporting_event: "Traffic police daytime work permit restriction",
    supporting_document: "City Traffic Police Restriction Advisory Order CTP/CBE/2024/07",
    approved_extension: true,
    extension_days: 20,
    agency_id: "AG-COI-05",
    agency_name: "Kongu Infra Developments"
  },
  {
    project_id: "MPLAD018",
    project_name: "Street Lights",
    district: "Trichy",
    category: "Infrastructure",
    approved_amount: 1700000,
    spent_amount: 1650000,
    progress_percent: 80,
    delay_days: 8,
    completion_status: "Ongoing",
    delay_reason: "Material Supply Delay",
    supporting_event: "Transformer pole connection wait",
    supporting_document: "TNEB Trichy North Power Grid Tie-in Certificate",
    approved_extension: true,
    extension_days: 10,
    agency_id: "AG-TRI-06",
    agency_name: "Delta Buildcon Enterprises"
  },
  {
    project_id: "MPLAD019",
    project_name: "Anganwadi Building",
    district: "Chennai",
    category: "Education",
    approved_amount: 2600000,
    spent_amount: 2500000,
    progress_percent: 70,
    delay_days: 12,
    completion_status: "Ongoing",
    delay_reason: "Heavy Rainfall",
    supporting_event: "Intermittent cloudburst water recession wait",
    supporting_document: "Chennai Regional Meteorological Centre Weather Log RMC/CHE/2024/51",
    approved_extension: true,
    extension_days: 15,
    agency_id: "AG-CHE-07",
    agency_name: "Metro Urban Drainage Contractors"
  },
  {
    project_id: "MPLAD020",
    project_name: "Public Toilet",
    district: "Vellore",
    category: "Sanitation",
    approved_amount: 1400000,
    spent_amount: 1300000,
    progress_percent: 75,
    delay_days: 10,
    completion_status: "Ongoing",
    delay_reason: "Government Approval Delay",
    supporting_event: "Underground sewerage connection inspection",
    supporting_document: "Vellore TWAD Board Drainage Interconnection Approval",
    approved_extension: true,
    extension_days: 15,
    agency_id: "AG-VEL-02",
    agency_name: "Vellore Engineering Services"
  }
];
